version: '3.8'

services:
  # Serviço da Aplicação Web (Django + Gunicorn)
  web:
    build: .
    container_name: cryptotrader_web
    command: gunicorn crypto_trader.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - redis

  # Serviço do Redis (Broker para o Celery)
  redis:
    image: "redis:alpine"
    container_name: cryptotrader_redis
    ports:
      - "6379:6379"

  # Serviço do Celery Worker
  celery_worker:
    build: .
    container_name: cryptotrader_celery_worker
    command: celery -A crypto_trader worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

  # Serviço do Celery Beat (Agendador)
  celery_beat:
    build: .
    container_name: cryptotrader_celery_beat
    command: celery -A crypto_trader beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

volumes:
  static_volume:
